-- Video assets generated by Veo
CREATE TABLE marketing.base_video (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  filename             text NOT NULL,
  storage_path         text NOT NULL UNIQUE,
  prompt               text,
  source_image_id      uuid REFERENCES marketing.base_image(id),
  generation_prompt_id uuid REFERENCES marketing.generation_prompt(id),
  aspect_ratio         text NOT NULL,
  duration_seconds     integer NOT NULL,
  model_tier           text NOT NULL,  -- 'fast' | 'standard'
  created_at           timestamptz NOT NULL DEFAULT now(),
  archived_at          timestamptz
);

-- M2M: video <-> segment
CREATE TABLE marketing.base_video_segment (
  base_video_id uuid NOT NULL REFERENCES marketing.base_video(id) ON DELETE CASCADE,
  segment_id    uuid NOT NULL REFERENCES marketing.segment(id) ON DELETE CASCADE,
  PRIMARY KEY (base_video_id, segment_id)
);

-- RLS
ALTER TABLE marketing.base_video ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketing.base_video_segment ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated full access" ON marketing.base_video
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access" ON marketing.base_video_segment
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Grants (same pattern as other marketing tables)
GRANT ALL ON marketing.base_video TO authenticated;
GRANT ALL ON marketing.base_video_segment TO authenticated;
